### ISSUE TITLE
[Task]: fix `openExternalLinksInDifferentTab` interferring with cookiebot

### ISSUE THREAD

**Issue by begonaalvarezd** [boxfish-studio/liebling#28]
https://discord.com/channels/397872799483428865/1090642339669745745/1090642571631538186

It seems like that function is adding the `target="_blank"` to the cookiebot banner, only reproduceable in firefox, which opens a new tab every time the user interacts with cookiebot. It seems to be happening on shimmer & assembly blogs, not in iota, not sure why, but we should try to mitigate in all blogs 🙏🏼 and even the main iota website which I think has something similar

**Comment by evavirseda** [comment]
~~Reopened as it's still not working in `IOTA`~~
