### ISSUE TITLE
[Task]: Host google fonts in repo (iota blog)

### ISSUE THREAD

**Issue by begonaalvarezd** [boxfish-studio/liebling#8]
If we fetch google fonts from google URLs, we should download the font in the repository directly to avoid issues. 
https://twitter.com/jwildeboer/status/1562077629284585474?t=h7IDOqgQnWkTFWRGooxwyw&s=19

**Comment by evavirseda** [comment]
Looks good

![image](https://user-images.githubusercontent.com/72078237/186859896-1a7b9a97-1e25-47e3-b794-779bed648942.png)

**Comment by begonaalvarezd** [comment]
I can see a font in the blog, the branch where we store the iota changes is `feat/iota-blog`
![image](https://user-images.githubusercontent.com/3624944/186895884-8803a631-8e2d-4345-878b-1b89a1295c0b.png)
